INSERT INTO awd_translation (id, source, translation_value)
VALUES (1, 'Editor', 'Monteur'),
       (2, 'Supervising Film Editor', 'Monteur en chef'),
       (3, 'Additional Editing', 'Montage supplémentaire'),
       (4, 'Editorial Manager', 'Responsable éditorial'),
       (5, 'First Assistant Editor', 'Premier assistant monteur'),
       (6, 'Additional Editorial Assistant', 'Assistant éditorial supplémentaire'),
       (7, 'Editorial Coordinator', 'Coordinateur éditorial'),
       (8, 'Editorial Production Assistant', 'Assistant de production éditoriale'),
       (9, 'Editorial Services', 'Services éditoriaux'),
       (10, 'Archival Footage Coordinator', 'Coordinateur des archives vidéo'),
       (11, 'Archival Footage Research', E'Recherche d\'archives vidéo'),
       (12, 'Color Timer', 'Chronométreur couleur'),
       (13, 'Digital Intermediate', 'Intermédiaire numérique'),
       (14, 'Other', 'Autre'),
       (15, 'Assistant Editor', 'Assistant monteur'),
       (16, 'Associate Editor', 'Monteur associé'),
       (17, 'Co-Editor', 'Co-monteur'),
       (18, 'Negative Cutter', 'Monteur négatif'),
       (19, '3D Digital Colorist', 'Coloriste numérique 3D'),
       (20, '3D Editor', 'Monteur 3D'),
       (21, 'Additional Colorist', 'Coloriste supplémentaire'),
       (22, 'Additional Editor', 'Monteur supplémentaire'),
       (23, 'Assistant Picture Editor', 'Assistant monteur image'),
       (24, 'Atmos Editor', 'Monteur atmos'),
       (25, 'Color Assistant', 'Assistant couleur'),
       (26, 'Color Grading', 'Étalonnage couleur'),
       (27, 'Colorist', 'Coloriste'),
       (28, 'Consulting Editor', 'Monteur consultant'),
       (29, 'Dailies Manager', 'Responsable des rushs'),
       (30, 'Dailies Operator', 'Opérateur de rushs'),
       (31, 'Dailies Technician', 'Technicien de rushs'),
       (32, 'Digital Color Timer', 'Chronométreur couleur numérique'),
       (33, 'Digital Colorist', 'Coloriste numérique'),
       (34, 'Digital Conform Editor', 'Monteur de conformité numérique'),
       (35, 'Digital Intermediate Assistant', 'Assistant intermédiaire numérique'),
       (36, 'Digital Intermediate Colorist', 'Coloriste intermédiaire numérique'),
       (37, 'Digital Intermediate Data Wrangler', 'Gestionnaire de données intermédiaires numériques'),
       (38, 'Digital Intermediate Editor', 'Monteur intermédiaire numérique'),
       (39, 'Digital Intermediate Producer', 'Producteur intermédiaire numérique'),
       (40, 'Editorial Consultant', 'Consultant éditorial'),
       (41, 'EPK Editor', 'Monteur EPK'),
       (42, 'First Assistant Picture Editor', 'Premier assistant monteur image'),
       (43, 'Lead Editor', 'Monteur principal'),
       (44, 'Online Editor', 'Monteur en ligne'),
       (45, 'Project Manager', 'Chef de projet'),
       (46, 'Senior Colorist', 'Coloriste senior'),
       (47, 'Senior Digital Intermediate Colorist', 'Coloriste intermédiaire numérique senior'),
       (48, 'Stereoscopic Editor', 'Monteur stéréoscopique'),
       (49, 'Supervising Editor', 'Monteur superviseur');

INSERT INTO awd_translation (id, source, translation_value)
VALUES (50, 'Costume Design', 'Conception de costumes'),
       (51, 'Makeup Artist', 'Maquilleur'),
       (52, 'Hairstylist', 'Coiffeur'),
       (53, 'Set Dressing Artist', 'Décorateur de plateau'),
       (54, 'Set Dressing Supervisor', 'Superviseur de décor'),
       (55, 'Set Dressing Manager', 'Responsable du décor'),
       (56, 'Set Dressing Production Assistant', 'Assistant de production décor'),
       (57, 'Facial Setup Artist', 'Artiste de configuration faciale'),
       (58, 'Hair Setup', 'Installation capillaire'),
       (59, 'Costume Supervisor', 'Superviseur de costumes'),
       (60, 'Set Costumer', 'Costumier de plateau'),
       (61, 'Makeup Department Head', 'Chef du département maquillage'),
       (62, 'Wigmaker', 'Perruquier'),
       (63, 'Shoe Design', 'Conception de chaussures'),
       (64, 'Other', 'Autre'),
       (65, 'Co-Costume Designer', 'Co-concepteur de costumes'),
       (66, 'Hair Department Head', 'Chef du département capillaire'),
       (67, 'Hair Designer', 'Concepteur capillaire'),
       (68, 'Makeup Designer', 'Concepteur de maquillage'),
       (69, 'Assistant Costume Designer', 'Assistant concepteur de costumes'),
       (70, 'Prosthetic Supervisor', 'Superviseur de prothèses'),
       (71, 'Seamstress', 'Couturière'),
       (72, 'Key Hair Stylist', 'Coiffeur principal'),
       (73, 'Ager/Dyer', 'Vieillisseur/Teinturier'),
       (74, 'Costume Consultant', 'Consultant en costumes'),
       (75, 'Costume Coordinator', 'Coordinateur de costumes'),
       (76, 'Costume Illustrator', 'Illustrateur de costumes'),
       (77, 'Hair Supervisor', 'Superviseur capillaire'),
       (78, 'Key Costumer', 'Costumier principal'),
       (79, 'Key Makeup Artist', 'Maquilleur principal'),
       (80, 'Key Set Costumer', 'Costumier principal de plateau'),
       (81, 'Makeup Effects Designer', E'Concepteur d\'effets de maquillage'),
       (82, 'Makeup Supervisor', 'Superviseur de maquillage'),
       (83, 'Prosthetic Designer', 'Concepteur de prothèses'),
       (84, 'Prosthetic Makeup Artist', 'Maquilleur de prothèses'),
       (85, 'Tailor', 'Tailleur'),
       (86, 'Tattoo Designer', 'Concepteur de tatouages'),
       (87, 'Wardrobe Supervisor', 'Superviseur de garde-robe'),
       (88, 'Wig Designer', 'Concepteur de perruques'),
       (89, 'Additional Hairstylist', 'Coiffeur supplémentaire'),
       (90, 'Additional Wardrobe Assistant', 'Assistant de garde-robe supplémentaire'),
       (91, 'Assistant Hairstylist', 'Assistant coiffeur'),
       (92, 'Assistant Hairdresser', 'Assistant coiffeur'),
       (93, 'Assistant Makeup Artist', 'Assistant maquilleur'),
       (94, 'Contact Lens Designer', 'Concepteur de lentilles de contact'),
       (95, 'Contact Lens Painter', 'Peintre de lentilles de contact'),
       (96, 'Contact Lens Technician', 'Technicien de lentilles de contact'),
       (97, 'Costume Assistant', 'Assistant costume'),
       (98, 'Costume Mistress', 'Maîtresse de costumes'),
       (99, 'Costume Designer', 'Concepteur de costumes'),
       (100, 'Costume Set Supervisor', 'Superviseur de costumes de plateau'),
       (101, 'Costume Standby', 'Costumier de réserve'),
       (102, 'Costumer', 'Costumier'),
       (103, 'Daily Makeup & Hair', 'Maquillage et coiffure quotidienne'),
       (104, 'Daily Wardrobe', 'Garde-robe quotidienne'),
       (105, 'Dresser', 'Assistant habilleur'),
       (106, 'Extras Dresser', E'Habilleur d\'extras'),
       (107, 'Extras Makeup Artist', E'Maquilleur d\'extras'),
       (108, 'First Assistant Hairstylist', 'Premier assistant coiffeur'),
       (109, 'First Assistant Makeup Artist', 'Premier assistant maquilleur'),
       (110, 'Hair Assistant', 'Assistant coiffure'),
       (111, 'Hairdresser', 'Coiffeur'),
       (112, 'Key Dresser', 'Habilleur principal'),
       (113, 'Key Hairdresser', 'Coiffeur principal'),
       (114, 'Lead Costumer', 'Costumier principal'),
       (115, 'Makeup & Hair', 'Maquillage et coiffure'),
       (116, 'Makeup & Hair Assistant', 'Assistant maquillage et coiffure'),
       (117, 'Makeup Trainee', 'Stagiaire maquillage'),
       (118, 'On Set Dresser', 'Habilleur sur plateau'),
       (119, 'Principal Costumer', 'Costumier principal'),
       (120, 'Prosthetics', 'Prothèses'),
       (121, 'Prosthetics Painter', 'Peintre de prothèses'),
       (122, 'Prosthetics Sculptor', 'Sculpteur de prothèses'),
       (123, 'Special Effects Key Makeup Artist', E'Maquilleur principal d\'effets spéciaux'),
       (124, 'Special Effects Makeup Artist', E'Maquilleur d\'effets spéciaux'),
       (125, 'Truck Costumer', 'Costumier de camion'),
       (126, 'Truck Supervisor', 'Superviseur de camion'),
       (127, 'Wardrobe Assistant', 'Assistant de garde-robe'),
       (128, 'Wardrobe Coordinator', 'Coordinateur de garde-robe'),
       (129, 'Wardrobe Designer', 'Concepteur de garde-robe'),
       (130, 'Wardrobe Intern', 'Stagiaire en garde-robe'),
       (131, 'Wardrobe Master', 'Maître de garde-robe'),
       (132, 'Wardrobe Specialized Technician', 'Technicien spécialisé en garde-robe');

INSERT INTO awd_translation (id, source, translation_value)
VALUES (133, 'Actor', 'Acteur'),
       (134, 'Stunt Double', 'Doublure cascade'),
       (135, 'Voice', 'Voix'),
       (136, 'Cameo', 'Caméo'),
       (137, 'Special Guest', 'Invité spécial'),
       (138, 'Screenplay', 'Scénario'),
       (139, 'Author', 'Auteur'),
       (140, 'Novel', 'Roman'),
       (141, 'Characters', 'Personnages'),
       (142, 'Theatre Play', 'Pièce de théâtre'),
       (143, 'Adaptation', 'Adaptation'),
       (144, 'Dialogue', 'Dialogue'),
       (145, 'Writer', 'Scénariste'),
       (146, 'Other', 'Autre'),
       (147, 'Storyboard', 'Storyboard'),
       (148, 'Original Story', 'Histoire originale'),
       (149, 'Scenario Writer', 'Scénariste'),
       (150, 'Screenstory', 'Scénario'),
       (151, 'Musical', 'Musical'),
       (152, 'Idea', 'Idée'),
       (153, 'Story', 'Histoire'),
       (154, 'Creative Producer', 'Producteur créatif'),
       (155, 'Teleplay', 'Téléfilm'),
       (156, 'Opera', 'Opéra'),
       (157, 'Co-Writer', 'Co-scénariste'),
       (158, 'Book', 'Livre'),
       (159, 'Comic Book', 'Bande dessinée'),
       (160, 'Short Story', 'Nouvelle'),
       (161, 'Series Composition', 'Composition de la série'),
       (162, 'Script Editor', 'Éditeur de script'),
       (163, 'Script Consultant', 'Consultant en script'),
       (164, 'Story Editor', E'Éditeur de l\'histoire'),
       (165, 'Executive Story Editor', E'Éditeur exécutif d\'histoire'),
       (166, 'Graphic Novel', 'Roman graphique'),
       (167, 'Head of Story', 'Chef du récit'),
       (168, 'Junior Story Editor', E'Jeune éditeur d\'histoire'),
       (169, 'Lyricist', 'Parolier'),
       (170, 'Original Concept', 'Concept original'),
       (171, 'Original Film Writer', 'Scénariste original du film'),
       (172, 'Original Series Creator', 'Créateur original de la série'),
       (173, 'Senior Story Editor', E'Éditeur principal d\'histoire'),
       (174, 'Staff Writer', 'Scénariste'),
       (175, 'Story Artist', E'Artiste d\'histoire'),
       (176, 'Story Consultant', 'Consultant en histoire'),
       (177, 'Story Coordinator', E'Coordinateur d\'histoire'),
       (178, 'Story Developer', E'Développeur d\'histoire'),
       (179, 'Story Manager', E'Gestionnaire d\'histoire'),
       (180, 'Story Supervisor', E'Superviseur d\'histoire'),
       (181, E'Writers\' Assistant', 'Assistant scénariste'),
       (182, E'Writers\' Production', 'Production de scénaristes'),
       (183, 'Director of Photography', 'Directeur de la photographie'),
       (184, 'Underwater Camera', 'Caméra sous-marine'),
       (185, 'Camera Operator', 'Opérateur de caméra'),
       (186, 'Still Photographer', 'Photographe'),
       (187, 'Camera Department Manager', 'Chef du département caméra'),
       (188, 'Camera Supervisor', 'Superviseur de caméra'),
       (189, 'Camera Technician', 'Technicien caméra'),
       (190, 'Other', 'Autre'),
       (191, 'Grip', 'Grip'),
       (192, 'Steadicam Operator', 'Opérateur Steadicam'),
       (193, 'Additional Camera', 'Caméra supplémentaire'),
       (194, 'Camera Intern', 'Stagiaire caméra'),
       (195, 'Additional Photography', 'Photographie supplémentaire'),
       (196, 'Helicopter Camera', 'Caméra hélicoptère'),
       (197, 'First Assistant Camera', 'Premier assistant caméra'),
       (198, 'Additional Still Photographer', 'Photographe supplémentaire'),
       (199, 'Aerial Camera', 'Caméra aérienne'),
       (200, 'Aerial Camera Technician', 'Technicien caméra aérienne'),
       (201, 'Aerial Director of Photography', 'Directeur de la photographie aérienne'),
       (202, 'Camera Loader', 'Chargeur de caméra'),
       (203, 'Dolly Grip', 'Grip Dolly'),
       (204, 'Epk Camera Operator', 'Opérateur de caméra EPK'),
       (205, 'Key Grip', 'Chef grip'),
       (206, 'Russian Arm Operator', 'Opérateur de bras russe'),
       (207, 'Second Unit Director of Photography', 'Directeur de la photographie de la deuxième équipe'),
       (208, 'Ultimate Arm Operator', 'Opérateur de bras ultime'),
       (209, 'Underwater Director of Photography', 'Directeur de la photographie sous-marine'),
       (210, '"A" Camera Operator', 'Opérateur de caméra "A"'),
       (211, '"B" Camera Operator', 'Opérateur de caméra "B"'),
       (212, '"C" Camera Operator', 'Opérateur de caméra "C"'),
       (213, '"D" Camera Operator', 'Opérateur de caméra "D"');

INSERT INTO awd_translation (id, source, translation_value)
VALUES (215, 'Additional Director of Photography', 'Directeur de la photographie supplémentaire'),
       (216, 'Additional First Assistant Camera', 'Premier assistant caméra supplémentaire'),
       (217, 'Additional Grip', 'Poignée supplémentaire'),
       (218, 'Additional Key Grip', 'Chef machiniste supplémentaire'),
       (219, 'Additional Second Assistant Camera', 'Deuxième assistant caméra supplémentaire'),
       (220, 'Additional Set Photographer', 'Photographe de plateau supplémentaire'),
       (221, 'Additional Underwater Photography', 'Photographie sous-marine supplémentaire'),
       (222, 'Assistant Camera', 'Assistant caméra');

INSERT INTO awd_translation (id, source, translation_value)
VALUES (223, 'Assistant Grip', 'Assistant machiniste'),
       (224, 'Best Boy Grip', 'Chef machiniste'),
       (225, 'BTS Footage', 'Images BTS'),
       (226, 'BTS Photographer', 'Photographe BTS'),
       (227, 'BTS Videographer', 'Vidéaste BTS'),
       (228, 'Camera Car', 'Voiture caméra'),
       (229, 'Camera Department Production Assistant', 'Assistant de production département caméra'),
       (230, 'Camera Production Assistant', 'Assistant de production caméra'),
       (231, 'Camera Trainee', 'Stagiaire caméra'),
       (232, 'Camera Truck', 'Camion caméra'),
       (233, 'Clapper Loader', 'Chargeur de clap'),
       (234, 'Data Wrangler', 'Responsable de la gestion des données'),
       (235, 'Digital Imaging Technician', 'Technicien en imagerie numérique'),
       (236, 'Drone Cinematographer', 'Cinéaste drone'),
       (237, 'Drone Pilot', 'Pilote de drone'),
       (238, 'Epk Director', 'Réalisateur EPK'),
       (239, 'Epk Producer', 'Producteur EPK'),
       (240, 'First Assistant "A" Camera', 'Premier assistant caméra "A"'),
       (241, 'First Assistant "B" Camera', 'Premier assistant caméra "B"'),
       (242, 'First Assistant "C" Camera', 'Premier assistant caméra "C"'),
       (243, 'First Assistant "D" Camera', 'Premier assistant caméra "D"'),
       (244, 'First Company Grip', 'Chef machiniste de la première équipe'),
       (245, 'Focus Puller', 'Opérateur de mise au point'),
       (246, 'Head of Layout', 'Responsable de la disposition'),
       (247, 'Jimmy Jib Operator', 'Opérateur Jimmy Jib'),
       (248, 'Libra Head Technician', 'Technicien de tête Libra'),
       (249, 'Phantom Operator', 'Opérateur Phantom'),
       (250, 'Red Technician', 'Technicien Red'),
       (251, 'Second Assistant "A" Camera', 'Deuxième assistant caméra "A"'),
       (252, 'Second Assistant "B" Camera', 'Deuxième assistant caméra "B"'),
       (253, 'Second Assistant "C" Camera', 'Deuxième assistant caméra "C"'),
       (254, 'Second Assistant "D" Camera', 'Deuxième assistant caméra "D"'),
       (255, 'Second Assistant Camera', 'Deuxième assistant caméra'),
       (256, 'Second Company Grip', 'Chef machiniste de la deuxième équipe'),
       (257, 'Set Photographer', 'Photographe de plateau'),
       (258, 'Third Assistant "A" Camera', 'Troisième assistant caméra "A"'),
       (259, 'Third Assistant "B" Camera', 'Troisième assistant caméra "B"'),
       (260, 'Third Assistant "C" Camera', 'Troisième assistant caméra "C"'),
       (261, 'Third Assistant "D" Camera', 'Troisième assistant caméra "D"'),
       (262, 'Third Assistant Camera', 'Troisième assistant caméra'),
       (263, 'Underwater Epk Photographer', 'Photographe EPK sous-marin'),
       (264, 'Underwater Stills Photographer', E'Photographe d\'images fixes sous-marin'),
       (265, 'Videojournalist', 'Vidéojournaliste'),
       (266, 'Video Report', 'Reportage vidéo');

INSERT INTO awd_translation (id, source, translation_value)
VALUES (267, 'Producer', 'Producteur'),
       (268, 'Executive Producer', 'Producteur exécutif'),
       (269, 'Casting', 'Casting'),
       (270, 'Production Manager', 'Directeur de production'),
       (271, 'Unit Production Manager', 'Directeur de production unitaire'),
       (272, 'Line Producer', 'Producteur délégué'),
       (273, 'Location Manager', 'Responsable des lieux'),
       (274, 'Other', 'Autre'),
       (275, 'Production Supervisor', 'Superviseur de production'),
       (276, 'Production Accountant', 'Comptable de production'),
       (277, 'Production Office Coordinator', 'Coordinateur de bureau de production'),
       (278, 'Finance', 'Finances'),
       (279, 'Executive Consultant', 'Consultant exécutif'),
       (280, 'Character Technical Supervisor', 'Superviseur technique des personnages'),
       (281, 'Development Manager', 'Responsable du développement'),
       (282, 'Administration', 'Administration'),
       (283, 'Executive In Charge Of Post Production', 'Responsable exécutif de la post-production'),
       (284, 'Production Director', 'Directeur de production'),
       (285, 'Executive In Charge Of Production', 'Responsable exécutif de la production'),
       (286, 'Publicist', 'Attaché de presse'),
       (287, 'Associate Producer', 'Producteur associé'),
       (288, 'Co-Producer', 'Co-producteur'),
       (289, 'Co-Executive Producer', 'Co-producteur exécutif'),
       (290, 'Casting Associate', 'Associé de casting'),
       (291, 'Researcher', 'Chercheur'),
       (292, 'Production Coordinator', 'Coordinateur de production'),
       (293, 'Consulting Producer', 'Producteur consultant'),
       (294, 'Supervising Producer', 'Producteur superviseur'),
       (295, 'Senior Executive Consultant', 'Consultant exécutif senior'),
       (296, 'Unit Manager', E'Chef d\'équipe'),
       (297, 'ADR Voice Casting', 'Casting voix ADR'),
       (298, 'Assistant Production Coordinator', 'Assistant coordinateur de production'),
       (299, 'Assistant Production Manager', 'Assistant directeur de production'),
       (300, 'Casting Assistant', 'Assistant de casting'),
       (301, 'Casting Consultant', 'Consultant de casting'),
       (302, 'Coordinating Producer', 'Producteur coordinateur'),
       (303, 'Local Casting', 'Casting local'),
       (304, 'Script Researcher', 'Chercheur de scénario'),
       (305, 'Accountant', 'Comptable'),
       (306, 'Accounting Clerk Assistant', 'Assistant comptable'),
       (307, 'Accounting Supervisor', 'Superviseur comptable'),
       (308, 'Accounting Trainee', 'Stagiaire comptable'),
       (309, 'Additional Casting', 'Casting supplémentaire'),
       (310, 'Additional Production Assistant', 'Assistant de production supplémentaire'),
       (311, 'Additional Post-Production Supervisor', 'Superviseur supplémentaire de post-production'),
       (312, 'Art Department Production Assistant', 'Assistant de production département artistique'),
       (313, 'Assistant Accountant', 'Comptable assistant'),
       (314, 'Assistant Extras Casting', 'Assistant de casting de figurants'),
       (315, 'Assistant Location Manager', 'Assistant de responsable des lieux'),
       (316, 'Assistant Unit Manager', E'Assistant chef d\'équipe'),
       (317, 'Attorney', 'Avocat'),
       (318, 'Background Casting Director', 'Directeur de casting de figurants'),
       (319, 'Back-up Set Production Assistant', 'Assistant de production de secours'),
       (320, 'Back-up Truck Production Assistant', 'Assistant de production camion de secours'),
       (321, 'Broadcast Producer', 'Producteur de diffusion'),
       (322, 'Business Affairs Coordinator', 'Coordinateur des affaires commerciales'),
       (323, 'Casting Coordinator', 'Coordinateur de casting'),
       (324, 'Casting Director', 'Directeur de casting'),
       (325, 'Casting Producer', 'Producteur de casting'),
       (326, 'Casting Researcher', 'Chercheur de casting'),
       (327, 'Consulting Accountant', 'Comptable consultant'),
       (328, 'Contract Manager', 'Responsable de contrat'),
       (329, 'Controller', 'Contrôleur'),
       (330, 'Data Management Technician', 'Technicien en gestion des données'),
       (331, 'Delegated Producer', 'Producteur délégué'),
       (332, 'Development Producer', 'Producteur de développement'),
       (333, 'Director of Operations', 'Directeur des opérations'),
       (334, 'Executive Assistant', 'Assistant exécutif'),
       (335, 'Executive Co-Producer', 'Co-producteur exécutif'),
       (336, E'Executive Producer\'s Assistant', 'Assistant du producteur exécutif'),
       (337, 'Extras Casting', 'Casting de figurants'),
       (338, 'Extras Casting Assistant', 'Assistant de casting de figurants'),
       (339, 'Extras Casting Coordinator', 'Coordinateur de casting de figurants'),
       (340, 'Feature Finishing Producer', 'Producteur de finition de caractéristiques'),
       (341, 'Finishing Producer', 'Producteur de finition'),
       (342, 'First Assistant Accountant', 'Premier assistant comptable'),
       (343, 'First Assistant Production Coordinator', 'Premier assistant coordinateur de production'),
       (344, 'General Manager', 'Directeur général'),
       (345, 'Grip Production Assistant', 'Assistant de production Grip'),
       (346, 'Head of Production', 'Directeur de production'),
       (347, 'Head of Programming', 'Chef de la programmation'),
       (348, 'Head of Research', 'Chef de la recherche'),
       (349, 'Human Resources', 'Ressources humaines'),
       (350, 'Insert Unit Location Manager', E'Directeur de l\'emplacement de l\'unité d\'insertion'),
       (351, 'Key Accountant', 'Comptable principal'),
       (352, 'Key Art Production Assistant', 'Assistant de production clé en art'),
       (353, 'Key Grip Production Assistant', 'Assistant de production clé Grip'),
       (354, 'Key Production Assistant', 'Assistant de production clé'),
       (355, 'Key Set Production Assistant', 'Assistant de production clé'),
       (356, 'Locale Casting Director', 'Directeur de casting local'),
       (357, 'Location Assistant', 'Assistant de localisation'),
       (358, 'Location Casting', 'Casting de localisation'),
       (359, 'Location Coordinator', 'Coordinateur de localisation'),
       (360, 'Location Production Assistant', 'Assistant de production de localisation'),
       (361, 'Musical Casting', 'Casting musical'),
       (362, 'Original Casting', 'Casting original'),
       (363, 'Payroll Accountant', 'Comptable de paie'),
       (364, 'Post Coordinator', 'Coordinateur de poste'),
       (365, 'Post Producer', 'Producteur après production'),
       (366, 'Post Production Accountant', 'Comptable de postproduction'),
       (367, 'Post Production Coordinator', 'Coordinateur de postproduction'),
       (368, 'Post Production Producer', 'Producteur après production'),
       (369, 'Post Production Technical Engineer', 'Ingénieur technique de postproduction'),
       (370, E'Producer\'s Assistant', 'Assistant du producteur'),
       (371, 'Production Assistant', 'Assistant de production'),
       (372, 'Production Consultant', 'Consultant en production'),
       (373, 'Production Designer', 'Designer de production'),
       (374, 'Production Driver', 'Conducteur de production'),
       (375, 'Production Executive', 'Cadre de production'),
       (376, 'Production Runner', 'Coureur de production'),
       (377, 'Production Secretary', 'Secrétaire de production'),
       (378, 'Production Trainee', 'Stagiaire de production'),
       (379, 'Research Assistant', 'Assistant de recherche'),
       (380, 'Second Assistant Accountant', 'Deuxième assistant comptable'),
       (381, 'Second Assistant Production Coordinator', 'Deuxième assistant coordinateur de production'),
       (382, 'Second Assistant Unit Manager', E'Deuxième assistant chef d\'unité'),
       (383, 'Second Unit Location Manager', E'Directeur de l\'emplacement de la deuxième unité'),
       (384, 'Street Casting', 'Casting de rue'),
       (385, 'Trainee Production Coordinator', 'Stagiaire coordinateur de production'),
       (386, 'Travel Coordinator', 'Coordinateur de voyage'),
       (387, 'Truck Production Assistant', 'Assistant de production de camion'),
       (388, 'Unit Swing', 'Unité Swing'),
       (389, 'Special Effects', 'Effets spéciaux'),
       (390, 'Post Production Supervisor', 'Superviseur de postproduction'),
       (391, 'Second Unit', 'Deuxième unité'),
       (392, 'Choreographer', 'Chorégraphe'),
       (393, 'Stunts', 'Cascadeurs'),
       (394, 'Stunt Coordinator', 'Coordinateur de cascades'),
       (395, 'Special Effects Coordinator', 'Coordinateur des effets spéciaux'),
       (396, 'Supervising Technical Director', 'Directeur technique de supervision'),
       (397, 'Supervising Animator', 'Animateur superviseur'),
       (398, 'Production Artist', 'Artiste de production'),
       (399, 'Sequence Lead', 'Séquence principale'),
       (400, 'Second Film Editor', 'Deuxième monteur de film'),
       (401, 'Temp Music Editor', 'Éditeur de musique temporaire'),
       (402, 'Temp Sound Editor', 'Éditeur de son temporaire'),
       (403, 'Sequence Supervisor', 'Superviseur de séquence'),
       (404, 'Software Team Lead', E'Chef d\'équipe logicielle'),
       (405, 'Software Engineer', 'Ingénieur logiciel'),
       (406, 'Documentation & Support', 'Documentation et support'),
       (407, 'Machinist', 'Machiniste'),
       (408, 'Photoscience Manager', 'Directeur de la photoscience'),
       (409, 'Department Administrator', 'Administrateur du département'),
       (410, 'Schedule Coordinator', 'Coordinateur de planning'),
       (411, 'Supervisor of Production Resources', 'Superviseur des ressources de production'),
       (412, 'Production Office Assistant', 'Assistant de bureau de production'),
       (413, 'Information Systems Manager', E'Directeur des systèmes d\'information'),
       (414, 'Systems Administrators & Support', 'Administrateurs et support systèmes'),
       (415, 'Projection', 'Projection'),
       (416, 'Post Production Assistant', 'Assistant de postproduction'),
       (417, 'Sound Design Assistant', 'Assistant en conception sonore'),
       (418, 'Mix Technician', 'Technicien de mixage'),
       (419, 'Motion Actor', 'Acteur de mouvement'),
       (420, 'Sets & Props Supervisor', 'Superviseur des décors et accessoires'),
       (421, 'Compositor', 'Compositeur'),
       (422, 'Tattooist', 'Tatoueur'),
       (423, 'Sets & Props Artist', 'Artiste des décors et accessoires'),
       (424, 'Motion Capture Artist', 'Artiste de capture de mouvement'),
       (425, 'Sequence Artist', 'Artiste de séquence'),
       (426, 'Mixing Engineer', 'Ingénieur de mixage'),
       (427, 'Special Sound Effects', 'Effets sonores spéciaux'),
       (428, 'Post-Production Manager', 'Directeur de postproduction'),
       (429, 'Dialect Coach', 'Coach de dialecte'),
       (430, 'Picture Car Coordinator', 'Coordinateur de voitures de film'),
       (431, 'Cableman', 'Monteur de câbles'),
       (432, 'Set Production Assistant', 'Assistant de production de plateau'),
       (433, 'Video Assist Operator', E'Opérateur d\'assistance vidéo'),
       (434, 'Unit Publicist', E'Attaché de presse de l\'unité'),
       (435, 'Set Medic', 'Médecin de plateau'),
       (436, 'Stand In', 'Doublure'),
       (437, 'Transportation Coordinator', 'Coordinateur de transport'),
       (438, 'Transportation Captain', 'Capitaine de transport'),
       (439, 'Post Production Consulting', 'Consultant en postproduction'),
       (440, 'Production Intern', 'Stagiaire de production'),
       (441, 'Utility Stunts', 'Cascadeur utilitaire'),
       (442, E'Actor\'s Assistant', E'Assistant d\'acteur'),
       (443, 'Set Production Intern', 'Stagiaire de production de plateau'),
       (444, 'Production Controller', 'Contrôleur de production'),
       (445, 'Studio Teacher', 'Professeur de studio'),
       (446, 'Chef', 'Chef'),
       (447, 'Craft Service', E'Service d\'artisanat'),
       (448, 'Scenic Artist', 'Artiste de scène'),
       (449, 'Propmaker', 'Fabricant de décors'),
       (450, 'Prop Maker', 'Fabricant de décors'),
       (451, 'Transportation Co-Captain', 'Co-capitaine du transport'),
       (452, 'Driver', 'Chauffeur'),
       (453, 'Security', 'Sécurité'),
       (454, 'Second Unit Cinematographer', 'Directeur de la photographie de la deuxième unité'),
       (455, 'Loader', 'Chargeur'),
       (456, 'Manager of Operations', 'Directeur des opérations'),
       (457, 'Quality Control Supervisor', 'Superviseur de contrôle de qualité'),
       (458, 'Legal Services', 'Services juridiques'),
       (459, 'Public Relations', 'Relations publiques'),
       (460, 'Score Engineer', 'Ingénieur de score'),
       (461, 'Translator', 'Traducteur'),
       (462, 'Title Graphics', 'Graphiques de titre'),
       (463, 'Telecine Colorist', 'Coloriste téléciné'),
       (464, 'Animatronic and Prosthetic Effects', 'Effets animatroniques et prothétiques'),
       (465, 'Martial Arts Choreographer', E'Chorégraphe d\'arts martiaux'),
       (466, 'Cinematography', 'Cinématographie'),
       (467, 'Steadycam', 'Steadycam'),
       (468, 'Executive Visual Effects Producer', E'Producteur exécutif d\'effets visuels'),
       (469, 'Visual Effects Design Consultant', E'Consultant en design d\'effets visuels'),
       (470, 'Digital Effects Supervisor', 'Superviseur des effets numériques'),
       (471, 'Digital Producer', 'Producteur numérique'),
       (472, 'CG Supervisor', 'Superviseur CG'),
       (473, 'Visual Effects Art Director', 'Directeur artistique des effets visuels'),
       (474, 'Visual Effects Editor', E'Éditeur d\'effets visuels'),
       (475, 'Executive in Charge of Finance', 'Cadre financier'),
       (476, 'Associate Choreographer', 'Chorégraphe associé'),
       (477, 'Makeup Effects', 'Effets de maquillage'),
       (478, 'Treatment', 'Traitement'),
       (479, 'Dramaturgy', 'Dramaturgie'),
       (480, 'Lighting Camera', E'Caméra d\'éclairage'),
       (481, 'Technical Supervisor', 'Superviseur technique'),
       (482, 'CGI Supervisor', 'Superviseur CGI'),
       (483, 'Creative Consultant', 'Consultant créatif'),
       (484, 'Script', 'Script'),
       (485, 'Executive Music Producer', 'Producteur musical exécutif'),
       (486, 'Commissioning Editor', 'Éditeur de commission'),
       (487, 'Additional Writing', 'Écriture supplémentaire'),
       (488, 'Additional Music', 'Musique additionnelle'),
       (489, 'Poem', 'Poème'),
       (490, 'Thanks', 'Remerciements'),
       (491, 'Creator', 'Créateur'),
       (492, 'Additional Dialogue', 'Dialogue supplémentaire'),
       (493, 'Video Game', 'Jeu vidéo'),
       (494, 'Graphic Novel Illustrator', 'Illustrateur de roman graphique'),
       (495, 'Other', 'Autre'),
       (496, 'Series Writer', 'Scénariste de série'),
       (497, 'Radio Play', 'Pièce radiophonique'),
       (498, 'Armorer', 'Armurier'),
       (499, 'Carpenter', 'Charpentier'),
       (500, 'Editorial Staff', 'Personnel éditorial'),
       (501, 'Aerial Coordinator', 'Coordinateur aérien'),
       (502, 'Animal Coordinator', 'Coordinateur animalier'),
       (503, 'Animal Wrangler', 'Dresseur animalier'),
       (504, 'Animatronics Designer', E'Designer d\'animatronique'),
       (505, 'Drone Operator', 'Opérateur de drone'),
       (506, 'In Memory Of', 'À la mémoire de'),
       (507, 'Pilot', 'Pilote'),
       (508, 'Presenter', 'Présentateur'),
       (509, 'Animatronics Supervisor', E'Superviseur d\'animatronique'),
       (510, 'Armory Coordinator', E'Coordinateur de l\'armurerie'),
       (511, 'Digital Effects Producer', E'Producteur d\'effets numériques'),
       (512, 'Fight Choreographer', 'Chorégraphe de combat'),
       (513, 'Marine Coordinator', 'Coordinateur maritime'),
       (514, 'Pyrotechnician', 'Pyrotechnicien'),
       (515, 'Techno Crane Operator', 'Opérateur de grue technologique'),
       (516, 'Acting Double', E'Doublure d\'acteur'),
       (517, 'Additional Script Supervisor', 'Superviseur de script additionnel'),
       (518, 'Administrative Assistant', 'Assistant administratif'),
       (519, 'Assistant Chef', 'Assistant cuisinier'),
       (520, 'Assistant Craft Service', E'Assistant du service d\'artisanat'),
       (521, 'Assistant Picture Car Coordinator', 'Assistant coordinateur des voitures de film'),
       (522, 'Assistant Script', 'Assistant de script'),
       (523, 'Assistant Vehicles Coordinator', 'Assistant coordinateur des véhicules'),
       (524, 'Base Camp Operator', 'Opérateur du camp de base'),
       (525, 'Captain Driver', 'Chauffeur de capitaine'),
       (526, 'Cast Driver', 'Chauffeur de casting'),
       (527, 'Catering', 'Restauration'),
       (528, 'Catering Head Chef', 'Chef de cuisine de la restauration'),
       (529, 'Chaperone', 'Chaperon'),
       (530, 'Chaperone Tutor', 'Tuteur de chaperon'),
       (531, 'Charge Scenic Artist', 'Artiste scénique chargé'),
       (532, 'Child Wrangler', E'Dresseur d\'enfants'),
       (533, 'Clearances Coordinator', 'Coordinateur de clairance'),
       (534, 'Clearances Consultant', 'Conseiller de clairance'),
       (535, 'Dialogue Coach', 'Coach de dialogue'),
       (536, 'Digital Supervisor', 'Superviseur numérique'),
       (537, 'Director of Communications', 'Directeur de la communication'),
       (538, 'File Footage', E'Images d\'archives'),
       (539, 'Film Processor', 'Traitement de film'),
       (540, 'Floor Runner', 'Coureur de plateau'),
       (541, 'Generator Operator', 'Opérateur de générateur'),
       (542, 'Head Driver', 'Chauffeur principal'),
       (543, 'Health and Safety', 'Santé et sécurité'),
       (544, 'Interactive Manager', 'Gestionnaire interactif'),
       (545, 'Intern', 'Stagiaire'),
       (546, 'Key Scenic Artist', 'Artiste scénique clé'),
       (547, 'Key Special Effects', 'Effets spéciaux clés'),
       (548, 'Logistics Coordinator', 'Coordinateur logistique'),
       (549, 'Marine Pilot', 'Pilote maritime'),
       (550, 'Master at Arms', E'Maître d\'armes'),
       (551, 'Medical Consultant', 'Consultant médical'),
       (552, 'Military Consultant', 'Consultant militaire'),
       (553, 'Playback Coordinator', 'Coordinateur de lecture'),
       (554, 'Police Consultant', 'Consultant de police'),
       (555, 'Post Production Scripts', 'Scripts de postproduction'),
       (556, 'Receptionist', 'Réceptionniste'),
       (557, 'Scientific Consultant', 'Consultant scientifique'),
       (558, 'Security Coordinator', 'Coordinateur de sécurité'),
       (559, 'Series Publicist', 'Attaché de presse de la série'),
       (560, 'Set Runner', 'Coureur de plateau'),
       (561, 'Special Effects Assistant', 'Assistant des effets spéciaux'),
       (562, 'Special Effects Best Boy', 'Meilleur garçon des effets spéciaux'),
       (563, 'Special Effects Manager', 'Directeur des effets spéciaux'),
       (564, 'Special Effects Technician', 'Technicien des effets spéciaux'),
       (565, 'Specialized Driver', 'Chauffeur spécialisé'),
       (566, 'Sponsorship Coordinator', 'Coordinateur de parrainage'),
       (567, 'Sponsorship Director', 'Directeur de parrainage'),
       (568, 'Stunt Double', 'Doublure de cascade'),
       (569, 'Stunt Driver', 'Cascadeur conducteur'),
       (570, 'Supervising Armorer', 'Armurier superviseur'),
       (571, 'Technical Advisor', 'Conseiller technique'),
       (572, 'Transcriptions', 'Transcriptions'),
       (573, 'Unit Medic', E'Médecin d\'unité'),
       (574, 'Vehicles Coordinator', 'Coordinateur de véhicules'),
       (575, 'Vehicles Wrangler', 'Dresseur de véhicules'),
       (576, 'Weapons Master', E'Maître d\'armes'),
       (577, 'Weapons Wrangler', E'Dresseur d\'armes'),
       (578, 'Director', 'Réalisateur'),
       (579, 'Script Supervisor', 'Superviseur de script'),
       (580, 'Other', 'Autre'),
       (581, 'Layout', 'Mise en page'),
       (582, 'Script Coordinator', 'Coordinateur de script'),
       (583, 'Special Guest Director', 'Réalisateur invité spécial'),
       (584, 'Assistant Director', 'Assistant réalisateur'),
       (585, 'Co-Director', 'Co-réalisateur'),
       (586, 'Continuity', 'Continuité'),
       (587, 'First Assistant Director', 'Premier assistant réalisateur'),
       (588, 'Second Assistant Director', 'Deuxième assistant réalisateur'),
       (589, 'Third Assistant Director', 'Troisième assistant réalisateur'),
       (590, 'Action Director', 'Directeur des cascades'),
       (591, 'Additional Second Assistant Director', 'Deuxième assistant réalisateur supplémentaire'),
       (592, 'Additional Third Assistant Director', 'Troisième assistant réalisateur supplémentaire'),
       (593, 'Assistant Director Trainee', 'Stagiaire assistant réalisateur'),
       (594, 'Crowd Assistant Director', 'Assistant réalisateur de foule'),
       (595, 'Field Director', 'Directeur de terrain'),
       (596, 'First Assistant Director (Prep)', 'Premier assistant réalisateur (préparation)'),
       (597, 'First Assistant Director Trainee', 'Stagiaire premier assistant réalisateur'),
       (598, 'Insert Unit Director', E'Directeur d\'unité d\'insertion'),
       (599, 'Insert Unit First Assistant Director', E'Premier assistant réalisateur d\'unité d\'insertion'),
       (600, 'Second Assistant Director Trainee', 'Stagiaire deuxième assistant réalisateur'),
       (601, 'Second Second Assistant Director', 'Deuxième assistant réalisateur supplémentaire'),
       (602, 'Second Unit Director', 'Directeur de la seconde équipe'),
       (603, 'Second Unit First Assistant Director', 'Premier assistant réalisateur de la seconde équipe'),
       (604, 'Series Director', 'Réalisateur de la série'),
       (605, 'Stage Director', 'Metteur en scène'),
       (606, 'Production Design', 'Design de production'),
       (607, 'Art Direction', 'Direction artistique'),
       (608, 'Set Decoration', 'Décoration de plateau'),
       (609, 'Set Designer', 'Designer de plateau'),
       (610, 'Conceptual Design', 'Conception conceptuelle'),
       (611, 'Interior Designer', E'Designer d\'intérieur'),
       (612, 'Settings', 'Réglages'),
       (613, 'Assistant Art Director', 'Assistant directeur artistique'),
       (614, 'Art Department Coordinator', 'Coordinateur du département artistique'),
       (615, 'Assistant Property Master', 'Assistant du maître des accessoires'),
       (616, 'Other', 'Autre'),
       (617, 'Art Department Manager', 'Directeur du département artistique'),
       (618, 'Sculptor', 'Sculpteur'),
       (619, 'Art Department Assistant', 'Assistant du département artistique'),
       (620, 'Background Designer', E'Designer d\'arrière-plan'),
       (621, 'Co-Art Director', 'Co-directeur artistique'),
       (622, 'Set Decoration Buyer', 'Acheteur de décoration de plateau'),
       (623, 'Production Illustrator', 'Illustrateur de production'),
       (624, 'Standby Painter', 'Peintre de réserve'),
       (625, 'Property Master', 'Maître des accessoires'),
       (626, 'Location Scout', 'Éclaireur de lieu'),
       (627, 'Supervising Art Director', 'Directeur artistique superviseur'),
       (628, 'Leadman', E'Chef d\'équipe'),
       (629, 'Greensman', 'Homme de verdure'),
       (630, 'Gun Wrangler', E'Dresseur d\'armes à feu'),
       (631, 'Construction Coordinator', 'Coordinateur de construction'),
       (632, 'Construction Foreman', 'Contremaître de construction'),
       (633, 'Lead Painter', 'Peintre principal'),
       (634, 'Sign Painter', 'Peintre de signe'),
       (635, 'Painter', 'Peintre'),
       (636, 'Assistant Set Dresser', E'Assistant d\'habillage de plateau'),
       (637, 'Conceptual Illustrator', 'Illustrateur conceptuel'),
       (638, 'Draughtsman', 'Dessinateur'),
       (639, 'Lead Set Dresser', E'Chef d\'habillage de plateau'),
       (640, 'Prop Designer', E'Designer d\'accessoires'),
       (641, 'Set Decorating Coordinator', 'Coordinateur de décoration de plateau'),
       (642, 'Set Dresser', 'Habilleur de plateau'),
       (643, 'Storyboard Designer', 'Designer de storyboard'),
       (644, 'Title Designer', 'Designer de titre'),
       (645, 'Additional Construction', 'Construction supplémentaire'),
       (646, 'Additional Construction Grip', 'Poignée de construction supplémentaire'),
       (647, 'Additional Key Construction Grip', 'Poignée de construction clé supplémentaire'),
       (648, 'Additional Set Dresser', 'Habilleur de plateau supplémentaire'),
       (649, 'Additional Storyboarding', 'Storyboarding supplémentaire'),
       (650, 'Art Department Trainee', 'Stagiaire du département artistique'),
       (651, 'Art Designer', 'Designer artistique'),
       (652, 'Art Direction Intern', 'Stagiaire en direction artistique'),
       (653, 'Assistant Decorator', 'Décorateur assistant'),
       (654, 'Assistant Director of Photography', 'Assistant directeur de la photographie'),
       (655, 'Assistant Production Design', 'Assistant en design de production'),
       (656, 'Assistant Set Decoration Buyer', 'Assistant acheteur de décoration de plateau'),
       (657, 'Assistant Set Decoration', 'Assistant décoration de plateau'),
       (658, 'Assistant Set Designer', 'Assistant designer de plateau'),
       (659, 'Assistant Set Propsman', 'Assistant de plateau'),
       (660, 'Concept Artist', 'Artiste conceptuel'),
       (661, 'Construction Buyer', 'Acheteur de construction'),
       (662, 'Construction Grip', 'Poignée de construction'),
       (663, 'Construction Manager', 'Gestionnaire de construction'),
       (664, 'Creative Director', 'Directeur créatif'),
       (665, 'Daily Grip', 'Poignée quotidienne'),
       (666, 'Decorator', 'Décorateur'),
       (667, 'Digital Storyboarding', 'Storyboard numérique'),
       (668, 'Dressing Prop', 'Accessoiriste'),
       (669, 'First Assistant Art Direction', 'Première assistante direction artistique'),
       (670, 'First Assistant Property Master', 'Premier assistant maître des accessoires'),
       (671, 'Graphic Designer', 'Graphiste'),
       (672, 'Head Carpenter', 'Charpentier en chef'),
       (673, 'Head Decorator', 'Décorateur en chef'),
       (674, 'Head Designer', 'Designer en chef'),
       (675, 'Head Greensman', 'Chef des hommes de verdure'),
       (676, 'Helping Hand', E'Main d\'aide'),
       (677, 'Key Carpenter', 'Charpentier clé'),
       (678, 'Key Construction Grip', 'Poignée de construction clé'),
       (679, 'Key Set Painter', 'Peintre de plateau clé'),
       (680, 'Main Title Designer', 'Designer de titre principal'),
       (681, 'On Set Computer Graphics', 'Graphiques informatiques sur le plateau'),
       (682, 'On Set Key Props', 'Accessoires clés sur le plateau'),
       (683, 'On Set Props', 'Accessoires sur le plateau'),
       (684, 'Opening Title Sequence', E'Séquence de titre d\'ouverture'),
       (685, 'Original Series Design', 'Conception originale de la série'),
       (686, 'Paint Coordinator', 'Coordinateur de peinture'),
       (687, 'Petty Cash Buyer', 'Acheteur de petite caisse'),
       (688, 'Property Builder', E'Constructeur d\'accessoires'),
       (689, 'Property Buyer', E'Acheteur d\'accessoires'),
       (690, 'Property Graphic Designer', E'Designer graphique d\'accessoires'),
       (691, 'Props', 'Accessoires'),
       (692, 'Runner Art Department', 'Coureur du département artistique'),
       (693, 'Second Assistant Art Director', 'Deuxième assistant directeur artistique'),
       (694, 'Set Dressing Buyer', E'Acheteur d\'habillage de plateau'),
       (695, 'Set Painter', 'Peintre de plateau'),
       (696, 'Set Propsman', 'Accessoiriste de plateau'),
       (697, 'Set Supervisor', 'Superviseur de plateau'),
       (698, 'Set Buyer', 'Acheteur de plateau'),
       (699, 'Shop Electric', 'Électricien boutique'),
       (700, 'Special Props', 'Accessoires spéciaux'),
       (701, 'Standby Art Director', 'Directeur artistique de secours'),
       (702, 'Standby Carpenter', 'Menuisier de secours'),
       (703, 'Standby Property Master', 'Responsable des accessoires de secours'),
       (704, 'Storyboard Artist', 'Artiste de storyboard'),
       (705, 'Storyboard Assistant', 'Assistant de storyboard'),
       (706, 'Supervising Carpenter', 'Menuisier superviseur'),
       (707, 'Swing', 'Balancement'),
       (708, 'Textile Artist', 'Artiste textile'),
       (709, 'Title Illustration', 'Illustration de titre'),
       (710, 'Web Designer', 'Designer Web'),
       (711, 'Animation', 'Animation'),
       (712, 'Visual Effects', 'Effets visuels'),
       (713, 'Chief Technician / Stop-Motion Expert', 'Technicien en chef / Expert en animation image par image'),
       (714, 'Creature Design', 'Conception de créatures'),
       (715, 'Shading', 'Ombrage'),
       (716, 'Modeling', 'Modélisation'),
       (717, 'CG Painter', 'Peintre CG'),
       (718, 'Visual Development', 'Développement visuel'),
       (719, 'Animation Manager', E'Gestionnaire d\'animation'),
       (720, 'Animation Director', E'Directeur d\'animation'),
       (721, 'Fix Animator', 'Animateur de correction'),
       (722, 'Animation Department Coordinator', E'Coordinateur du département d\'animation'),
       (723, 'Animation Fix Coordinator', E'Coordinateur de correction d\'animation'),
       (724, 'Animation Production Assistant', E'Assistant de production d\'animation'),
       (725, 'Visual Effects Supervisor', 'Superviseur des effets visuels'),
       (726, 'Mechanical & Creature Designer', 'Concepteur mécanique et de créatures'),
       (727, 'Battle Motion Coordinator', 'Coordinateur de mouvement de bataille'),
       (728, 'Animation Supervisor', E'Superviseur d\'animation'),
       (729, 'VFX Supervisor', 'Superviseur VFX'),
       (730, 'Cloth Setup', 'Configuration de tissu'),
       (731, 'VFX Artist', 'Artiste VFX'),
       (732, 'CG Engineer', 'Ingénieur CG'),
       (733, '24 Frame Playback', 'Lecture 24 images par seconde'),
       (734, 'Imaging Science', E'Science de l\'imagerie'),
       (735, 'I/O Supervisor', E'Superviseur d\'E/S'),
       (736, 'Visual Effects Producer', E'Producteur d\'effets visuels'),
       (737, 'VFX Production Coordinator', 'Coordinateur de production VFX'),
       (738, 'I/O Manager', 'Gestionnaire E/S'),
       (739, 'Additional Effects Development', E'Développement d\'effets supplémentaires'),
       (740, 'Color Designer', 'Designer couleur'),
       (741, 'Simulation & Effects Production Assistant', E'Assistant de production de simulation et d\'effets'),
       (742, 'Simulation & Effects Artist', E'Artiste de simulation et d\'effets'),
       (743, 'Pyrotechnic Supervisor', 'Superviseur pyrotechnique'),
       (744, 'Special Effects Supervisor', 'Superviseur des effets spéciaux'),
       (745, '3D Supervisor', 'Superviseur 3D'),
       (746, '3D Director', 'Directeur 3D'),
       (747, 'Digital Compositor', 'Compositeur numérique'),
       (748, 'Visual Effects Coordinator', 'Coordinateur des effets visuels'),
       (749, 'VFX Editor', 'Éditeur VFX'),
       (750, '2D Artist', 'Artiste 2D'),
       (751, '2D Supervisor', 'Superviseur 2D'),
       (752, '3D Animator', 'Animateur 3D'),
       (753, '3D Artist', 'Artiste 3D'),
       (754, '3D Coordinator', 'Coordinateur 3D'),
       (755, '3D Generalist', 'Généraliste 3D'),
       (756, '3D Modeller', 'Modélisateur 3D'),
       (757, '3D Sequence Supervisor', 'Superviseur de séquence 3D'),
       (758, '3D Tracking Layout', 'Mise en page de suivi 3D'),
       (759, 'CG Animator', 'Animateur CG'),
       (760, 'CGI Director', 'Directeur CGI'),
       (761, 'Character Designer', 'Concepteur de personnages'),
       (762, 'Character Modelling Supervisor', 'Superviseur de modélisation de personnages'),
       (763, 'Creature Technical Director', 'Directeur technique de créatures'),
       (764, 'Digital Effects Producer', E'Producteur d\'effets numériques'),
       (765, 'Key Animation', 'Animation clé'),
       (766, 'Lead Animator', 'Animateur principal'),
       (767, 'Lead Character Designer', 'Concepteur de personnages principal'),
       (768, 'Matchmove Supervisor', 'Superviseur de Matchmove'),
       (769, 'Mechanical Designer', 'Concepteur mécanique'),
       (770, 'Opening/Ending Animation', E'Animation d\'ouverture/de fin'),
       (771, 'Pre-Visualization Supervisor', 'Superviseur de prévisualisation'),
       (772, 'Roto Supervisor', 'Superviseur de Roto'),
       (773, 'Stereoscopic Coordinator', 'Coordinateur stéréoscopique'),
       (774, 'VFX Director of Photography', 'Directeur de la photographie VFX'),
       (775, 'VFX Lighting Artist', 'Artiste lumière VFX'),
       (776, 'Visual Effects Designer', E'Concepteur d\'effets visuels'),
       (777, 'Visual Effects Technical Director', 'Directeur technique des effets visuels'),
       (778, '2D Sequence Supervisor', 'Superviseur de séquence 2D'),
       (779, 'Additional Visual Effects', 'Effets visuels supplémentaires'),
       (780, 'Animation Coordinator', E'Coordinateur d\'animation'),
       (781, 'Animation Technical Director', E'Directeur technique d\'animation'),
       (782, 'CG Artist', 'Artiste CG'),
       (783, 'Compositing Artist', 'Artiste en composition'),
       (784, 'Compositing Lead', 'Chef de composition'),
       (785, 'Compositing Supervisor', 'Superviseur de composition'),
       (786, 'Creature Effects Technical Director', 'Directeur technique des effets de créature'),
       (787, 'Cyber Scanning Supervisor', 'Superviseur de numérisation cybernétique'),
       (788, 'Digital Film Recording', 'Enregistrement numérique du film'),
       (789, 'Director of Previsualization', 'Directeur de la prévisualisation'),
       (790, 'Effects Supervisor', 'Superviseur des effets'),
       (791, 'Generalist', 'Généraliste'),
       (792, 'Head of Animation', E'Responsable de l\'animation'),
       (793, 'Layout Supervisor', 'Superviseur de mise en page'),
       (794, 'Lead Creature Designer', 'Concepteur de créatures principal'),
       (795, 'Matte Painter', 'Peintre matte'),
       (796, 'Modelling Supervisor', 'Superviseur de modélisation'),
       (797, 'Pipeline Technical Director', 'Directeur technique de pipeline'),
       (798, 'Photo Retouching', 'Retouche photo'),
       (799, 'Pre-Visualization Coordinator', 'Coordinateur de prévisualisation'),
       (800, 'Rotoscoping Artist', 'Artiste de roto'),
       (801, 'Senior Animator', 'Animateur sénior'),
       (802, 'Senior Generalist', 'Généraliste Senior'),
       (803, 'Senior Modeller', 'Modélisateur Senior'),
       (804, 'Senior Visual Effects Supervisor', 'Superviseur Senior des effets visuels'),
       (805, 'Smoke Artist', 'Artiste de la fumée'),
       (806, 'Stereoscopic Supervisor', 'Superviseur stéréoscopique'),
       (807, 'Stereoscopic Technical Director', 'Directeur technique stéréoscopique'),
       (808, 'Supervising Animation Director', E'Directeur d\'animation superviseur'),
       (809, 'Visual Effects Assistant Editor', 'Assistant monteur des effets visuels'),
       (810, 'Visual Effects Camera', 'Caméra des effets visuels'),
       (811, 'Visual Effects Compositor', 'Compositeur des effets visuels'),
       (812, 'Visual Effects Director', 'Directeur des effets visuels'),
       (813, 'Visual Effects Lineup', 'Alignement des effets visuels'),
       (814, 'Visual Effects Production Assistant', 'Assistant de production des effets visuels'),
       (815, 'Visual Effects Production Manager', 'Gestionnaire de production des effets visuels'),
       (816, 'Lighting Technician', 'Technicien lumière'),
       (817, 'Best Boy Electric', 'Second électro'),
       (818, 'Gaffer', 'Chef électricien'),
       (819, 'Rigging Gaffer', 'Chef gréeur'),
       (820, 'Lighting Supervisor', 'Superviseur lumière'),
       (821, 'Lighting Manager', 'Responsable lumière'),
       (822, 'Directing Lighting Artist', 'Artiste lumière directionnelle'),
       (823, 'Master Lighting Artist', 'Maître artiste lumière'),
       (824, 'Lighting Artist', 'Artiste lumière'),
       (825, 'Lighting Coordinator', 'Coordinateur lumière'),
       (826, 'Lighting Production Assistant', 'Assistant de production lumière'),
       (827, 'Best Boy Electrician', 'Électricien Second'),
       (828, 'Electrician', 'Électricien'),
       (829, 'Rigging Grip', 'Gréeur'),
       (830, 'Other', 'Autre'),
       (831, 'Chief Lighting Technician', 'Technicien lumière en chef'),
       (832, 'Lighting Director', 'Directeur lumière'),
       (833, 'Rigging Supervisor', 'Superviseur gréeur'),
       (834, 'Underwater Gaffer', 'Chef électricien sous-marin'),
       (835, 'Additional Gaffer', 'Chef électricien supplémentaire'),
       (836, 'Additional Lighting Technician', 'Technicien lumière supplémentaire'),
       (837, 'Assistant Chief Lighting Technician', 'Assistant technicien lumière en chef'),
       (838, 'Assistant Electrician', 'Assistant électricien'),
       (839, 'Assistant Gaffer', 'Assistant chef électricien'),
       (840, 'Best Boy Lighting Technician', 'Technicien lumière second'),
       (841, 'Daily Electrics', 'Électros journaliers'),
       (842, 'Genetator Operator', 'Opérateur de générateur'),
       (843, 'Key Rigging Grip', 'Gréeur clé'),
       (844, 'Lighting Design', 'Conception lumière'),
       (845, 'Lighting Programmer', 'Programmeur lumière'),
       (846, 'O.B. Lighting', 'Éclairage O.B.'),
       (847, 'Standby Rigger', 'Gréeur de secours'),
       (848, 'Original Music Composer', 'Compositeur de musique originale'),
       (849, 'Sound Designer', 'Designer sonore'),
       (850, 'Sound Editor', 'Monteur son'),
       (851, 'Sound Director', 'Directeur sonore'),
       (852, 'Sound Mixer', 'Mixeur son'),
       (853, 'Music Editor', 'Monteur de musique'),
       (854, 'Sound Effects Editor', E'Monteur d\'effets sonores'),
       (855, 'Production Sound Mixer', 'Mixeur de son en production'),
       (856, 'Additional Soundtrack', 'Bande sonore supplémentaire'),
       (857, 'Supervising Sound Editor', 'Monteur son supervisant'),
       (858, 'Supervising Sound Effects Editor', E'Monteur d\'effets sonores supervisant'),
       (859, 'Sound Re-Recording Mixer', 'Mixeur de réenregistrement sonore'),
       (860, 'Recording Supervision', E'Supervision d\'enregistrement'),
       (861, 'Boom Operator', 'Perchman'),
       (862, 'Sound Montage Associate', 'Associé au montage sonore'),
       (863, 'Songs', 'Chansons'),
       (864, 'Music', 'Musique'),
       (865, 'ADR & Dubbing', 'ADR et doublage'),
       (866, 'Sound Recordist', 'Enregistreur sonore'),
       (867, 'Sound Engineer', 'Ingénieur du son'),
       (868, 'Foley', 'Foley'),
       (869, 'Dialogue Editor', 'Monteur de dialogue'),
       (870, 'Additional Music Supervisor', 'Superviseur de musique supplémentaire'),
       (871, 'First Assistant Sound Editor', 'Premier assistant monteur son'),
       (872, 'Scoring Mixer', 'Mixeur de la partition'),
       (873, 'Dolby Consultant', 'Consultant Dolby'),
       (874, 'Other', 'Autre'),
       (875, 'Music Director', 'Directeur musical'),
       (876, 'Orchestrator', 'Orchestrateur'),
       (877, 'Vocal Coach', 'Coach vocal'),
       (878, 'Music Supervisor', 'Superviseur musical'),
       (879, 'Sound', 'Son'),
       (880, 'Musician', 'Musicien'),
       (881, 'Additional Sound Re-Recording Mixer', 'Mixeur de réenregistrement sonore supplémentaire'),
       (882, 'Additional Sound Re-Recordist', 'Réenregistreur sonore supplémentaire'),
       (883, 'ADR Editor', 'Monteur ADR'),
       (884, 'ADR Supervisor', 'Superviseur ADR'),
       (885, 'Apprentice Sound Editor', 'Apprenti monteur son'),
       (886, 'Assistant Music Supervisor', 'Assistant superviseur de musique'),
       (887, 'Assistant Sound Editor', 'Assistant monteur son'),
       (888, 'Conductor', E'Chef d\'orchestre'),
       (889, 'Foley Editor', 'Monteur Foley'),
       (890, 'Music Programmer', 'Programmeur musical'),
       (891, 'Music Score Producer', 'Producteur de la partition musicale'),
       (892, 'Playback Singer', 'Chanteur de doublage'),
       (893, 'Sound Effects', 'Effets sonores'),
       (894, 'Sound Effects Designer', E'Designer d\'effets sonores'),
       (895, 'Supervising ADR Editor', 'Monteur ADR supervisant'),
       (896, 'Supervising Dialogue Editor', 'Monteur de dialogue supervisant'),
       (897, 'Supervising Music Editor', 'Monteur musical supervisant'),
       (898, 'Theme Song Performance', 'Interprétation de la chanson thème'),
       (899, 'Utility Sound', 'Son utilitaire'),
       (900, 'Additional Production Sound Mixer', 'Mixeur de son de production supplémentaire'),
       (901, 'ADR Editor', 'Monteur ADR'),
       (902, 'ADR Engineer', 'Ingénieur ADR'),
       (903, 'ADR Coordinator', 'Coordinateur ADR'),
       (904, 'ADR Mixer', 'Mixeur ADR'),
       (905, 'ADR Post Producer', 'Producteur post-AVR'),
       (906, 'ADR Recording Engineer', E'Ingénieur d\'enregistrement ADR'),
       (907, 'ADR Recordist', 'Enregistreur ADR'),
       (908, 'Assistant Dialogue Editor', 'Assistant monteur de dialogue'),
       (909, 'Assistant Foley Artist', 'Assistant artiste Foley'),
       (910, 'Assistant Sound Designer', 'Assistant designer sonore'),
       (911, 'Assistant Sound Engineer', 'Assistant ingénieur du son'),
       (912, 'Audio Post Coordinator', 'Coordinateur post-audio'),
       (913, 'Digital Foley Artist', 'Artiste Foley numérique'),
       (914, 'Foley Artist', 'Artiste Foley'),
       (915, 'Foley Mixer', 'Mixeur Foley'),
       (916, 'Foley Recording Engineer', E'Ingénieur d\'enregistrement Foley'),
       (917, 'Foley Recordist', 'Enregistreur Foley'),
       (918, 'Foley Supervisor', 'Superviseur Foley'),
       (919, 'Joint ADR Mixer', 'Mixeur ADR conjoint'),
       (920, 'Keyboard Programmer', 'Programmeur de clavier'),
       (921, 'Location Sound Assistant', 'Assistant son sur site'),
       (922, 'Location Sound Mixer', 'Mixeur de son sur site'),
       (923, 'Location Sound Recordist', 'Enregistreur de son sur site'),
       (924, 'Loop Group Coordinator', 'Coordinateur de boucle de groupe'),
       (925, 'Main Title Theme Composer', 'Compositeur du thème principal'),
       (926, 'Music Arranger', 'Arrangeur musical'),
       (927, 'Music Co-Supervisor', 'Co-superviseur musical'),
       (928, 'Music Consultant', 'Conseiller musical'),
       (929, 'Music Coordinator', 'Coordinateur musical'),
       (930, 'Music Producer', 'Producteur de musique'),
       (931, 'Music Sound Design and Processing', 'Conception sonore et traitement musical'),
       (932, 'Music Supervision Assistant', 'Assistant de supervision musicale'),
       (933, 'O.B. Sound', 'Son O.B.'),
       (934, 'Second Assistant Sound', 'Second assistant son'),
       (935, 'Sound Assistant', 'Assistant sonore'),
       (936, 'Sound Mix Technician', 'Technicien de mixage sonore'),
       (937, 'Sound Post Production Coordinator', 'Coordinateur de post-production sonore'),
       (938, 'Sound Post Supervisor', 'Superviseur de post-production sonore'),
       (939, 'Sound Re-Recording Assistant', 'Assistant de réenregistrement sonore'),
       (940, 'Sound Supervisor', 'Superviseur sonore'),
       (941, 'Sound Technical Supervisor', 'Superviseur technique du son'),
       (942, 'Vocals', 'Voix');





