INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (2, 'MOVIE', 'RELEASE_DATE_BETWEEN', 2, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (3, 'MOVIE', 'RELEASE_DATE_BETWEEN', 3, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (4, 'MOVIE', 'RELEASE_DATE_BETWEEN', 4, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (5, 'MOVIE', 'RELEASE_DATE_BETWEEN', 5, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (6, 'MOVIE', 'RELEASE_DATE_BETWEEN', 6, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (7, 'MOVIE', 'RELEASE_DATE_BETWEEN', 7, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (8, 'MOVIE', 'RELEASE_DATE_BETWEEN', 8, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (13, 'MOVIE', 'RELEASE_DATE_BETWEEN', 13, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (14, 'MOVIE', 'RELEASE_DATE_BETWEEN', 14, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (15, 'MOVIE', 'RELEASE_DATE_BETWEEN', 15, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (16, 'MOVIE', 'RELEASE_DATE_BETWEEN', 16, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (17, 'MOVIE', 'RELEASE_DATE_BETWEEN', 17, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (18, 'MOVIE', 'RELEASE_DATE_BETWEEN', 18, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (19, 'MOVIE', 'RELEASE_DATE_BETWEEN', 19, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (20, 'MOVIE', 'RELEASE_DATE_BETWEEN', 20, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (21, 'MOVIE', 'RELEASE_DATE_BETWEEN', 21, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (26, 'MOVIE', 'RELEASE_DATE_BETWEEN', 26, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (27, 'MOVIE', 'RELEASE_DATE_BETWEEN', 27, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (28, 'MOVIE', 'RELEASE_DATE_BETWEEN', 28, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (29, 'MOVIE', 'RELEASE_DATE_BETWEEN', 29, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (30, 'MOVIE', 'RELEASE_DATE_BETWEEN', 30, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (31, 'MOVIE', 'RELEASE_DATE_BETWEEN', 31, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (32, 'MOVIE', 'RELEASE_DATE_BETWEEN', 32, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (33, 'MOVIE', 'RELEASE_DATE_BETWEEN', 33, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (34, 'MOVIE', 'RELEASE_DATE_BETWEEN', 34, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (35, 'MOVIE', 'RELEASE_DATE_BETWEEN', 35, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (36, 'MOVIE', 'RELEASE_DATE_BETWEEN', 36, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (37, 'MOVIE', 'RELEASE_DATE_BETWEEN', 37, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (38, 'MOVIE', 'RELEASE_DATE_BETWEEN', 38, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (39, 'MOVIE', 'RELEASE_DATE_BETWEEN', 39, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (40, 'MOVIE', 'RELEASE_DATE_BETWEEN', 40, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (41, 'MOVIE', 'RELEASE_DATE_BETWEEN', 41, '2022,2024');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (42, 'CREW', 'DEPARTMENT_IN', 2, 'Directing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (43, 'CREW', 'DEPARTMENT_IN', 13, 'Writing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (44, 'CREW', 'DEPARTMENT_IN', 14, 'Writing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (45, 'CREW', 'DEPARTMENT_IN', 15, 'Sound');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (46, 'CREW', 'DEPARTMENT_IN', 16, 'Sound');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (47, 'CREW', 'DEPARTMENT_IN', 17, 'Camera');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (48, 'CREW', 'DEPARTMENT_IN', 18, 'Editing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (49, 'CREW', 'DEPARTMENT_IN', 19, 'Costume & Make-Up,Art');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (50, 'CREW', 'DEPARTMENT_IN', 20, 'Art');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (51, 'CREW', 'DEPARTMENT_IN', 21, 'Visual Effects');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (52, 'CREW', 'DEPARTMENT_IN', 26, 'Directing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (53, 'CREW', 'DEPARTMENT_IN', 31, 'Writing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (54, 'CREW', 'DEPARTMENT_IN', 32, 'Writing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (55, 'CREW', 'DEPARTMENT_IN', 33, 'Art');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (56, 'CREW', 'DEPARTMENT_IN', 34, 'Costume & Make-Up,Art');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (57, 'CREW', 'DEPARTMENT_IN', 35, 'Costume & Make-Up,Art');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (58, 'CREW', 'DEPARTMENT_IN', 36, 'Camera');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (59, 'CREW', 'DEPARTMENT_IN', 37, 'Editing');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (60, 'CREW', 'DEPARTMENT_IN', 38, 'Sound');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (61, 'CREW', 'DEPARTMENT_IN', 39, 'Visual Effects');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (62, 'CREW', 'DEPARTMENT_IN', 40, 'Sound');
INSERT INTO awd_award_condition (id, condition_type, condition_name, award_id, value) VALUES (63, 'CREW', 'DEPARTMENT_IN', 41, 'Sound');
